# Generated by Django 4.2.4 on 2023-08-24 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AppDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=80)),
                ("rating", models.PositiveIntegerField()),
                ("genre", models.CharField(max_length=50)),
                ("score", models.DecimalField(decimal_places=4, max_digits=10)),
            ],
        ),
    ]
